### ISSUE TITLE
Investigate support for esqLOC (SQL precompiler for Windows)

### ISSUE THREAD

**Issue by alanradau** [OpenCobolIDE/OpenCobolIDE#103]
Was trying to compile SQL sample and had prog. crash at line  which was an EXEC statement, 

IDENTIFICATION DIVISION.
       PROGRAM-ID. esqlOCGetStart1.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       EXEC SQL
         BEGIN DECLARE SECTION
       END-EXEC.
       01  HOSTVARS.
           05 BUFFER               PIC X(1024).
           05 hVarD                PIC S9(5)V99.
           05 hVarC                PIC X(50).
           05 hVarN                PIC 9(12).
       EXEC SQL
          END DECLARE SECTION
       END-EXEC.
------------------------------------

Invalid level number 'EXEC'

**Comment by ColinDuquesnoy** [comment]
Which OS? Have you read the guide about SQL Cobol (http://opencobolide.readthedocs.org/en/latest/advanced.html#how-to-setup-dbpre-integration-with-opencobolide)? You need to use dbpre to work with SQL Cobol.

If you still have a problem, post your compiler/dbpre configuration.

**Comment by alanradau** [comment]
Windows 7 32 bit no have not read they guide yet.

**Comment by ColinDuquesnoy** [comment]
I'am afraid you're out of luck, dbpre is not supported on Windows (yet). The only solution you have right now is to work on linux.

**Comment by ColinDuquesnoy** [comment]
I forget to mention that if you can get dbpre to compile and work on windows (from the command line) than the IDE is ready to support it.

I just could not get dbpre to compile on windows (tried with both mingw and visual studio). As I am not a windows users, I haven't spend too much time on this but maybe you can find a solution.

You'll find more info [here](https://github.com/OpenCobolIDE/OpenCobolIDE/issues/82) and [there](https://github.com/OpenCobolIDE/OpenCobolIDE/pull/91)

**Comment by alanradau** [comment]
Hi Colin:

      Thanks I notice Sergey has come up with patch for SQL not sure though if it is the same as yours, have a look and let me know as this may be the solution, I already have Linux and actually just updated my Mint Stick last night was unaware that you could now update the programs on it, in the past you could only have the raw OS without the addition of new software or updates. Problem is still most are still using windows, as a matter of fact although my system is now 64 bit I am still running Windows 32 bit, the Linux installation is 64 bit.

       Okay so getting back to the compile issue, sure no problem I'll try anything once or twice besides the compile issue may be something really really simple. I have not done this in a very long time so am willing to do and even help but I may need some of your help along the way. Besides in addition to COBOL I should also be learning C and best way to learn a language is to learn to modify the source code. In addition they are going to need some help anyway with GNU COBOL as noSQL databases and cloud DB's are making the scene. I suspect somewhere along the line we will see integration of cloud and relational DB and that is going to take some tricks. Thanks though I really appreciate, my big problem that I don't switch over totally to Linux right away is 1 the market and 2 the learning curve is just to steep for the entire package. The tough part for me is the installation in Linux I have become so used to the MSI in windows that I have forgotten yet I recall a time even with DOS you had to manually install, same with teh mainframes. 


       Anyway have a look at Sergey's esqLOC and let me know if perhaps this is all that is needed without  dbpree.

https://sourceforge.net/p/open-cobol/discussion/contrib/thread/4057115f/
Date: Wed, 25 Feb 2015 06:08:58 -0800

**Comment by ColinDuquesnoy** [comment]
Hi Alan,

Thanks for the info, I was not aware of esqLOC. esqLOC and dbpre seems to be two different precompilers for GnuCobol. 

I've had a quick look at the thread you mentioned and it looks like it will be possible to support that precompiler on Windows (the compiler build they used to test esqLOC is supported by OpenCobolIDE). To add support for that precompiler, I'll have to change a few things in the preferences dialog (e.g. include an option to let the user choose either dbpre or esqlLoc and configure it) and add a compiler interface for that tool (execution + output parsing).

It's not a big work but it's unlikely that I'll find the time to work on this feature before a few days/weeks. 

Also, I must say that I am a bit annoyed that there are two tools that are doing the exact same thing (pre-compile cobol source code to make GnuCobol happy). Do you know if we should prefer one over the other? Does the GnuCobol team plan to include one pre-compiler in their official build? I'd like to avoid wasting my time maintaining two identical tools...

*I'm reopening this ticket (with an updated title) so that I don't loose track of this feature.*

**Comment by ColinDuquesnoy** [comment]
@abbhishek you might be interested by this feature

**Comment by alanradau** [comment]
Okay Collin:

No expert but I do have a suspicion, I have compiled the "Hello World" sample using both OpenCobolIDE and Zues, the compile crashes in Zues as you can see by the snapshot and yet with yours it Compiles clean. Now I also included the path statement with windows to show that there should not be a problem, however further investigation led me to this 
http://www.google.ca/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0CB8QFjAA&url=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F1065993%2Fhas-windows-7-fixed-the-255-character-file-path-limit&ei=CAzuVIuTFMO7ggTO8oPgDg&usg=AFQjCNFiq7c8pLSt_1btrBb7h3ZkMprAAw&sig2=yHCv-rFThtsd4YBurZRJqg&bvm=bv.86956481 ,d.eXY which could explain the problem with Zues. Note that there is a 255 character limit. So you are definitely ahead of the game.

Now my suggestion if you want to stay ahead is put a switch so that it would turn the OpenCOBOL SQL off and yours on, there may be reasons a user may want to use one over the other, that would be between you and Brians Group. On the upside though with both it means that it creates an area specific to your product and Open COBOL thus when Robert starts the Certification Process this is one of those hidden secrets that all the other IDE builders are looking to figure out for their product. 

Now regarding the NoSQL thing I have some ideas on that one, now just think rather than converting, the SQL DB sits in the background and there is a routine creating keys on the fly that communicates from the Cloud to the SQL DB. Been Playing with Couch and seems simple enough this is the HTML address of the database, left it open so as long as the computers on you should be able to reach it let me know http://127.0.0.1:5984/_utils/database.html?testdatabase it should bring up the testdatabase with the record. Anyway enough said and have also sent a screenshot.

Okay so finally(yes just about done), okay so looks like you need some help with abbhishek I see but don't know what it is or what it does but please let me know, you have tweaked my curiosity. So don't be to upset, this shows the importance of communication so there is no duplication of tasks, OpenCOBOL has but one contender even close and the trick is to stay ahead. As it is got lots of time these days, not much call for HP3000 COBOL, BASIC or SPL programmers or even for the IMAGE Database or MPE OS so faster I learn the new toolset the faster I can make some money once again but also keep in mind my finances are extremely limited and that's why I've taken so long to get this fare. That and I refuse to move to that other country where programmers and Analysts are worth maybe 6 bucks an our if they're lucky.
Date: Wed, 25 Feb 2015 08:42:57 -0800

**Comment by ColinDuquesnoy** [comment]
> as you can see by the snapshot

Sorry but what snapshot are you referring? Mail attachments are not showing up here on github. Please write your reply here on github instead of using your mail clients (this not just images, you also loose text formatting when you reply with a mail).

**Comment by alanradau** [comment]
Forgot Colin:

       One of the original problems I had with windows was the two stage compile in Open COBOL, the compiler actually creates a c source file and then it is picked up and compiled by the Open Source Compilers, during the pre-compile it created #includes for Windows Visual Studio Libraries which of course were missing unless you had a few thousand to fork over. So now Microsoft has released the binaries but unfortunately not the source code. So if the SQL piece is somewhere in there then this could be the problem and why it doesn't work properly. 

P.S. while on linkedin someone was saying there were some problems with environment variables and large programs using IDE Is this the case, if so has it been fixed, so far can give you no further information and don't know at this point if it a known issue. Let me know and I can check it out.

Date: Wed, 25 Feb 2015 08:42:57 -0800

**Comment by alanradau** [comment]
Sorry about that, anyway the "Hello World" program compiles using your IDE but if I use Zues I get an error on the compile when it tries to go for the config file in mingw 
---------------------------------------------------------------------------
      Zeus - Version 3.97u
      Copyright (c) Xidicone P/L 1993-2014.  All rights reserved.
---------------------------------------------------------------------------
 **** Unregistered Software. To be used for evaluation purposes only. ****
---------------------------------------------------------------------------


Using document type compiler options....

/mingw/share/gnu-cobol/config/default.conf: No such file or directory
Error: failed to load the initial config file

Now when I do a path statement it shows the Mingw path properly. 

Here is the path statement from the Windows Environment Variables, haven't checked to see if its the 255 limit issue or as I notice the path needs to be modified, going to check but anyway this is what everything looks like. As I said the screenshot of yours just shows the same program with a return code of 0 and a clean compile. Might just move the config file if that's the problem but your's compiles clean so just the SQL issue to deal with and besides note the evaluation thingy so lots of work.

C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Common Files\Microsoft Shared\Windows Live;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\Windows Live\Shared; C:\program files\mingw-w64\i686-4.9.2-posix-dwarf-rt_v3-rev1\mingw32\bin; C:\gnucobol\bin

Date: Wed, 25 Feb 2015 10:33:18 -0800

**Comment by ColinDuquesnoy** [comment]
> looks like you need some help with abbhishek I see but don't know what it is or what it does but please let me know, you have tweaked my curiosity.

No, @abbhishek is a user who created issue #82 (which is very similar to yours).

The ``@`` means a mention, read this: https://github.com/blog/821

Github provides a lots of nice tools on its tracker (mention to other users, references to other issue even across repositories). I can only encourage you to not use your mail client for github related things, just click on the "View on github link" at the end of any notification mail.

> One of the original problems I had with windows was the two stage compile in Open COBOL, the compiler actually creates a c source file and then it is picked up and compiled by the Open Source Compilers, during the pre-compile it created #includes for Windows Visual Studio Libraries which of course were missing unless you had a few thousand to fork over. So now Microsoft has released the binaries but unfortunately not the source code. So if the SQL piece is somewhere in there then this could be the problem and why it doesn't work properly.

cobc will try to invoke the same compiler as the one that was used to build it. If you're using a MinGW build of OpenCobol, cobc will use gcc to compile the generated c file. If you're using a Visual Studio build of OpenCobol, it will use the visual studio c compiler to compile the generated c file.

OpenCobolIDE ships with a mingw build of OpenCobol: http://www.opencobol.org/modules/bwiki/index.php?Assorted%20Documents (mingw is bundled too). The IDE just setup it's own environment variable so that the compiler can be detected (and other mingw installation ignored) and can work out of the box without requiring the user to setup anything.

> P.S. while on linkedin someone was saying there were some problems with environment variables and large programs using IDE Is this the case, if so has it been fixed, so far can give you no further information and don't know at this point if it a known issue. Let me know and I can check it out.

There was an environment variable issue with an old version( almost one year ago) that prevented the IDE from using the bundled mingw installation (the user's mingw version was used instead of the bundled one, leading to strange errors). This has been fixed a long time ago. But note that I am not using the IDE on windows so I might have missed some bugs (if nobody report them I cannot fix them obviously). 

I don't know anything about problems with large projects. I can only suppose they say that because the IDE works on a single file basis and does not have any concept of project (yet). See https://github.com/OpenCobolIDE/OpenCobolIDE/issues/84

> program compiles using your IDE but if I use Zues

I guess Zeus rely on your system configuration to find cobc+mingw while OpenCobolIDE rely on the bundled OpenCobol compiler.

**Comment by ColinDuquesnoy** [comment]
> Took a while but now I see what you are talking about. Took me a little bit to navigate, I was expecting a reply but all I could find was an edit button but that also makes sense to some degree. :)

No, there is "Leave a comment" text box and a "Comment" button at the bottom of the page. See:

![github](https://cloud.githubusercontent.com/assets/1681217/6378702/5a50f624-bd2d-11e4-8d2b-8aa26f3efdec.png)

The edit button is to edit your post (which I don't recommand because I don't get a notification for an edit, just for a new post).

**Comment by alanradau** [comment]
Okay now I found it thanks, sorry bout that but takes a little while to nav. around and this one is really new to me, love the cloud stuff though. Anyway now have work to do have linux on a stick so while you are addressing that issue I'm going to go have a heart to heart for the next little while with the linux sudo command, first gotta make sure my stick has enough space. Then back to work on the windows stuff. Thanks though, learned some new stuff and hopefully we have the issue resolved. But also keep in mind Oracle is moving away from MySQL and towards Berkley DB I notice MariaDB is also becoming cloud friendly and hoping they are right about compatibility with MySQL but did notice a different ODBC for marie so will have to test Sergey's and your code when the time comes.

**Comment by ColinDuquesnoy** [comment]
I have a first version of the esqlOC integration in OpenCobolIDE. I am going to release it tonight so that you can try it out (I'll let you know when it's done).

**Comment by ColinDuquesnoy** [comment]
@alanradau @abbhishek 

OpenCobolIDE 4.4 for Windows is available on launchpad: https://launchpad.net/cobcide/+download

Read the guide on how to setup esqlOC with the IDE: http://opencobolide.readthedocs.org/en/latest/advanced.html#esqloc-on-windows

And please, let me know if that worked for you. I've tested the OP's example, it compiled fine but I have not tested with a database.
