### ISSUE TITLE
bug reporter in IDE

### ISSUE THREAD

**Issue by Bofinken** [OpenCobolIDE/OpenCobolIDE#104]
I have tested the bug report facility on two computers running Win 7 and I cannot send the bug report

**Comment by ColinDuquesnoy** [comment]
Which step did not work? Did you manage to login?

**Comment by Bofinken** [comment]
I could login, but nothing happened when I pressed the submit button.
I got some trace files, but unsure how to submit them.

**Comment by ColinDuquesnoy** [comment]
> I could login, but nothing happened when I pressed the submit button.

Maybe a permission issue. I tested the bug report tool with my account only (which has all the permissions on this repo). I'll create a fake user and see if I can reproduce the issue.

> I got some trace files, but unsure how to submit them.

Well you can just paste the output here (between triple back quotes ``` for a better readability)

**Comment by ColinDuquesnoy** [comment]
I tested with a fake account and the report was successfully submitted (see issue #106 ). Not sure what your problem is exactly (log file will help).

**Comment by ColinDuquesnoy** [comment]
Ok so I changed the bug report system. I got rid of the github api (and the github3.py dependency). Now using a (very long) encoded url with all the information (including the application log). Surprisingly it [works](https://github.com/OpenCobolIDE/OpenCobolIDE/issues/new?title=%5BBug%5D+Test&body=qzd%0A%0A%23%23+System+information%0A%0A-+Operating+System%3A+Windows%0A-+OpenCobolIDE%3A+4.3.2%0A-+GnuCobol%3A+1.1.0%0A-+Python%3A+3.4.2+%2832bits%29%0A-+Qt%3A+4.8.6%0A-+PyQt%3A+4.11.3%0A-+pyqode.core%3A+2.5.0.dev0%0A-+pyqode.cobol%3A+2.5.0.dev0%0A-+pyqode.qt%3A+2.4.1%0A-+pygments%3A+2.0.1%0A-+QDarkStyle%3A+1.15%0A%0A%23%23+Application+log%0A%0A%60%60%60%0AINFO%3A%3Aopen_cobol_ide%3A%3Aversion%3A+4.3.2%0AINFO%3A%3Apyqode.core.widgets.splittable_tab_widget%3A%3Aregistered+editors%3A+{%27text%2Fplain%27%3A+%3Cclass+%27pyqode.core.widgets.code_edits.TextCodeEdit%27%3E%2C+%27text%2Fx-log%27%3A+%3Cclass+%27pyqode.core.widgets.code_edits.TextCodeEdit%27%3E%2C+%27text%2Fx-cobol%27%3A+%3Cclass+%27open_cobol_ide.view.editors.cobol.CobolCodeEdit%27%3E%2C+%27text%2Fx-plain%27%3A+%3Cclass+%27pyqode.core.widgets.code_edits.TextCodeEdit%27%3E}%0AINFO%3A%3Aopen_cobol_ide.compilers%3A%3AOpenCobol+compiler+v.1.1.0%0A%0A%60%60%60%0A). The new system is a lot more simple and should be more stable (and should fix your issue).

I am still not sure whether I'll release it as v4.3.2 or v4.4. It mainly depends on #103. If I can get this to work before tomorrrow evening, I'll release v4.4 on friday (or monday) otherwise I'll release v4.3.2.

**Comment by Bofinken** [comment]
<?xml version="1.0" encoding="UTF-16"?>

 
<file:///C:\Users\stefan\Google%20Drive\cobol\bugs\WER73F0.tmp.WERInternalMe
tadata.xml> <WERReportMetadata>
<file:///C:\Users\stefan\Google%20Drive\cobol\bugs\WER73F0.tmp.WERInternalMe
tadata.xml>
<OSVersionInformation><WindowsNTVersion>6.1</WindowsNTVersion><Build>7601
Service Pack 1</Build><Product>(0x1): Windows 7
Ultimate</Product><Edition>Ultimate</Edition><BuildString>7601.18717.amd64fr
e.win7sp1_gdr.150113-1808</BuildString><Revision>1130</Revision><Flavor>Mult
iprocessor
Free</Flavor><Architecture>X64</Architecture><LCID>1033</LCID></OSVersionInf
ormation>
<file:///C:\Users\stefan\Google%20Drive\cobol\bugs\WER73F0.tmp.WERInternalMe
tadata.xml>
<ProblemSignatures><EventType>APPCRASH</EventType><Parameter0>OpenCobolIDE.e
xe</Parameter0><Parameter1>4.3.1.0</Parameter1><Parameter2>53826f5e</Paramet
er2><Parameter3>QtCore4.dll</Parameter3><Parameter4>4.8.6.0</Parameter4><Par
ameter5>53cf1132</Parameter5><Parameter6>c0000005</Parameter6><Parameter7>00
108503</Parameter7></ProblemSignatures>
<file:///C:\Users\stefan\Google%20Drive\cobol\bugs\WER73F0.tmp.WERInternalMe
tadata.xml>
<DynamicSignatures><Parameter1>6.1.7601.2.1.0.256.1</Parameter1><Parameter2>
1053</Parameter2><Parameter22>0a9e</Parameter22><Parameter23>0a9e372d3b4ad19
135b953a78882e789</Parameter23><Parameter24>0a9e</Parameter24><Parameter25>0
a9e372d3b4ad19135b953a78882e789</Parameter25></DynamicSignatures>
<file:///C:\Users\stefan\Google%20Drive\cobol\bugs\WER73F0.tmp.WERInternalMe
tadata.xml>
<SystemInformation><MID>921CE736-0B89-4B87-B0D7-74BB441181DA</MID><SystemMan
ufacturer>System manufacturer</SystemManufacturer><SystemProductName>System
Product
Name</SystemProductName><BIOSVersion>3029</BIOSVersion></SystemInformation><
/WERReportMetadata>

 

  _____  

Från: Colin Duquesnoy [mailto:notifications@github.com] 
Skickat: den 4 mars 2015 15:58
Till: OpenCobolIDE/OpenCobolIDE
Kopia: Bofinken
Ämne: Re: [OpenCobolIDE] bug reporter in IDE (#104)

 

I could login, but nothing happened when I pressed the submit button.

Maybe a permission issue. I tested the bug report tool with my account only
(which has all the permissions on this repo). I'll create a fake user and
see if I can reproduce the issue.

I got some trace files, but unsure how to submit them.

Well you can just paste the output here (between triple back quotes ``` for
a better readability)

—
Reply to this email directly or view
<https://github.com/OpenCobolIDE/OpenCobolIDE/issues/104#issuecomment-771719
98>  it on GitHub.
<https://github.com/notifications/beacon/AGDDmFS8wjrnI1Zhkm-khLHU62z5BHOxks5
nxxT1gaJpZM4Do-Wv.gif>
