### ISSUE TITLE
[Enhancement] EOL conversion

### ISSUE THREAD

**Issue by Bofinken** [OpenCobolIDE/OpenCobolIDE#110]
when I edit files from a linux server on my windows machine, they get CR LF EOL, but I would like to keep the EOL as the file had in the beginning or set the default EOL to windows or linux in the Preferences

**Comment by ColinDuquesnoy** [comment]
Ok, this is a feature that first need to be implemented in pyQode. I'll open an issue there. Once it has been implemented I'll add an option to choose the EOL convention.

I would actually add two options:

- Preferred EOL: Platform specific, Linux, Mac, Windows
- Auto detect EOL: if true it will detect EOL and use it instead of the preferred EOL.

I need to know your preferred EOL for creating new files but the IDE could auto detect EOL of existing files and use it instead of the preferred EOL.

What do you think?

**Comment by Bofinken** [comment]
Yes preferred EOL on new files: Linux, Mac, Windows and auto detect EOL
preserving the current format.

 

 

  _____  

Från: Colin Duquesnoy [mailto:notifications@github.com] 
Skickat: den 10 mars 2015 20:16
Till: OpenCobolIDE/OpenCobolIDE
Kopia: Bofinken
Ämne: Re: [OpenCobolIDE] [Enhancement] EOL conversion (#110)

 

Ok, this is a feature that first need to be implemented in pyQode. I'll open
an issue there. Once it has been implemented I'll add an option to choose
the EOL convention.

I would actually add two options:

*	Preferred EOL: Platform specific, Linux, Mac, Windows
*	Auto detect EOL: if true it will detect EOL and use it instead of
the preferred EOL.

I need to know your preferred EOL for creating new files but the IDE could
auto detect EOL of existing files and use it instead of the preferred EOL.

What do you think?

—
Reply to this email directly or view
<https://github.com/OpenCobolIDE/OpenCobolIDE/issues/110#issuecomment-781266
25>  it on GitHub.
<https://github.com/notifications/beacon/AGDDmIoyehyNgxPJq09AZKRgL_gr60Geks5
nzzp_gaJpZM4Dserq.gif>
