### ISSUE TITLE
[Bug] Cannot compile with not-standard file extensions

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#150]
I've added .TEST to the file extension list in compiler preferences.

This lead to .TEST files showing up in file open/save dialog and adds the syntax highlighting. But compiling leads to an error message "unsupported file extension".

## System information

- OpenCobolIDE: 4.6.1
- Python: 3.4.3 (32bits)
- Qt: 5.4.1
- PyQt: 5.4.1
- pyqode.core: 2.6.3
- pyqode.cobol: 2.6.1
- pyqode.qt: 2.6.0
- pygments: 2.0.2
- QDarkStyle: 2.0

**Comment by ColinDuquesnoy** [comment]
The problem here is that you set an extension in UPPER CASE, the settings expect lower case extensions. I fixed it by always converting extensions to lower case (the ide check for both lower/upper extension when you open a file but you need to specify only the lower case version in the preferences).

**Comment by ColinDuquesnoy** [comment]
Should be fixed, please try again!

**Comment by GitMensch** [comment]
Works now. Thank you.

Additional to the change "Make sure settings extensions are lower case" I suggest to remove duplicates - I had some in because of entering the extensions twice (all lower and all upper case).

I'm not sure but I think it would be clearer to the user if both changes are done if the edit looses the focus and not only on reopening the preferences.

Side note: why do the extensions in the setting need the "." included? I think this is quite uncommon, isn't it?

**Comment by ColinDuquesnoy** [comment]
Looks like I forget this one, reopening for the next bug fix release.

> Side note: why do the extensions in the setting need the "." included? I think this is quite uncommon, isn't it?

Because `os.path.splitext` returns a dotted extension (e.g. ``.cbl``) and at the time I wrote most of the code I did not know about the [fnmatch](https://docs.python.org/2/library/fnmatch.html#module-fnmatch) function. It's unlikely that I change that in OCIDE...
