### ISSUE TITLE
[Bug] File system view empty if function lint is aborting

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#171]
Recognized in conjunction with #168:

log reads

```log
ERROR::pyqode.backend::something went bad with worker <function lint at 0x034C10C0>(data={'path': 'C:\\TEST.COB', 'code': [removed from log], 'encoding': 'cp1252'})
ERROR::pyqode.backend::Traceback (most recent call last):
ERROR::pyqode.backend::  File "c:\dev\pyqode.core\pyqode\core\backend\server.py", line 135, in _handle
ERROR::pyqode.backend::  File "C:\Dev\OpenCobolIDE\open_cobol_ide\linter.py", line 33, in lint
ERROR::pyqode.backend::PermissionError: [Errno 13] Permission denied: 'C:\\.oci1433411286.cbl'
```

From glancing over the source that the log entries show I don't see why the file system view is empty but as the error in the log has nothing to do with the file system view I think it should be updated nonetheless.

## System information

- OpenCobolIDE: 4.6.2
- Python: 3.4.3 (32bits)
- Qt: 5.4.1
- PyQt: 5.4.1
- pyqode.core: 2.7.0.dev2
- pyqode.cobol: 2.6.1
- pyqode.qt: 2.6.0
- pygments: 2.0.2

**Comment by ColinDuquesnoy** [comment]
I am not sure this is related to the linter failure, the traceback show up in the log for people to report but the exception is correctly handled and should not cause a failure with the backend process (otherwise you would have lost code completion and navigation panel).

There is probably another reason why this happen, I'll see if I can reproduce it when I'll be working on #168.

**Comment by ColinDuquesnoy** [comment]
I've never been able to reproduce this issue. Going to close it.

If that happen again, comment and I'll reopen.

**Comment by GitMensch** [comment]
I cannot reproduce it with 4.7-pre1, therefore I think this will stay closed :-)
