### ISSUE TITLE
[Question]: is there a project with an issue tracker for the new IDE available?

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#179]
If not: should I keep adding new entries here and they will be referenced as soon as the new IDE is up? Sounds like work not necessary...

**Comment by ColinDuquesnoy** [comment]
No not yet, the code is on my private server at the moment and will stay there until I consider it is ready enough for an alpha. So yes continue to add here, all the feature I could not make in time for the alpha will be linked from here ;)

**Comment by GitMensch** [comment]
What about starting the project and only push a readme for now? This way we all know the name of the new IDE and have the trackers, discussions and wiki about it there.

**Comment by ColinDuquesnoy** [comment]
Yes good idea. I'll setup an organisation and a repository during next week, after the release of OpenCobolIDE v4.6.2.

**Comment by ColinDuquesnoy** [comment]
I created a new organisation and repository for HackEdit: https://github.com/HackEdit/hackedit

I'll soon add a better readme together with a rough roadmap.

**Comment by GitMensch** [comment]
So OCIDE got the first backports from HackEdit - very nice.
Is there any release for HackEdit alpha and/or the OCIDE 4.7 release roughly planned?

**Comment by ColinDuquesnoy** [comment]
There is a roadmap for hackedit [here](https://github.com/HackEdit/hackedit/wiki/Roadmap) but no due date. It's very hard to set realistic due dates because it depends a lot on the amout of free time I can dedicate to the project (and that typically change everyday). I guess it will be ready in a few weeks...I am almost done, there are still a few features to implement for the cobol plugins (mainly the own parser thing).

The first alpha will be released on pypi only. 

For the second alpha, I will focus on packaging (including #158 as I need a similar system for the initial setup of plugins). 

After the second alpha, I'll start backporting some features to OCIDE 4.7.
