### ISSUE TITLE
[Enhancement] Preferences dialog: add std=none, use all available std's

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#182]
Not passing -std=none but passing no std at all.

BTW: Newer versions added -std=acu, it cannot harm to add it to OCIDE, too - or to be even better: check for .conf-files in config directory of compiler.

**Comment by ColinDuquesnoy** [comment]
Where do I find the config files on linux/osx? If there is no reliable way to scan for those configs file or if it fail there won't be any config available. Is there a way to call cobc so that it prints the available configs?

**Comment by GitMensch** [comment]
You can found them in COB_CONFIG_DIR (standard install would lead to /usr/local/share/$PACKAGENAME/config). **Newer** versions show this with cobc --info (and newest also if an environment var currently overrides this):

COB_CONFIG_DIR           : /usr/local/share/gnu-cobol/config
  env: COB_CONFIG_DIR    : /tmp/build/gnu-cobol-2.0/config

**Comment by ColinDuquesnoy** [comment]
On the distributions I am using (ArchLinux and KaOs) and on OS X (open-cobol installed via homebrew) those variables are not set...

Anyway since the new version will show this info, I think I'll wait it is widely available to do config parsing, in the meanwhile I'll just add a "None" entry to the combo box.
