### ISSUE TITLE
[Enhancement] Add option to show compiler and runtime configuration

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#215]
This is highly GnuCOBOL specific but it would be a nice addition.
If there's something wrong with the compiler/runtime it's important to know more details about the actual compiler/runtime. The standard display of ``cobc/cobcrun --version`` is often information enough but something like a button "more details" (where it's possible to view/save the information) would be nice.

Call ``cobc/cobcrun --info`` and ``cobcrun --runtime-env`` for the actual data (the options for cobcrun are relatively new and not implemented in earlier versions).

**Comment by ColinDuquesnoy** [comment]
Where would you like to see that information/button? In the about dialog, in the compiler preferences dialog or in the check compiler dialog?

**Comment by GitMensch** [comment]
The about dialog sounds best. The call should be possible even if the compiler is not working (as it's especial useful in this case).

**Comment by ColinDuquesnoy** [comment]
I imlemented this in hackedit. I've added a "More info" button next to the "Check compiler" button in the compiler preferences. This is not in the about dialog because you can have multiple compiler configurations in HackEdit so it makes sense to put it in the compiler config dialog.

Here are some screenshots (on Windows 10):

* compiler preferences:

![capturecompilersettings](https://cloud.githubusercontent.com/assets/1681217/10558066/e64a892c-74c2-11e5-8034-ad41e6e19604.PNG)

* ``cobc --info``

![capturecobcinfo](https://cloud.githubusercontent.com/assets/1681217/10558067/ec2c6414-74c2-11e5-9b1f-761296abaf7b.PNG)

* ``cobcrun --runtime-env`` (not supported by my compiler):

![capturecmdnotsupported](https://cloud.githubusercontent.com/assets/1681217/10558073/02a89208-74c3-11e5-978f-b55e2a1cb063.PNG)
suggest to add a **GnuCOBOL** tab to the about dialog with the output of both ``cobc --info`` and ``cobcrun --runtime-env``.

**Comment by GitMensch** [comment]
Marvelous.

**Comment by GitMensch** [comment]
Minor glitch, works fine: cobc --info**s**

**Comment by ColinDuquesnoy** [comment]
Good catch! Fixed.

**Comment by GitMensch** [comment]
The output doesn't work on the machine I currently test. For cobcrun it just says:

~~~~~
cobcrun --runtime-env
=====================

cannot run command, cobcrun could not be found using PATH.
~~~~~

It works if I do this from command line... the verbose log has *NO* entry for the About->GnuCOBOL tab at all.

Please add the checks and commands that are done in About->GnuCOBOL tab to the debug log and recheck if the PATH setting from Preferences->compiler is honoured. Thank you

System information: 4.7 preview 2 on windows with own compiler/cobcrun

**Comment by ColinDuquesnoy** [comment]
> the PATH setting from Preferences->compiler is honoured

This is the reason, I am not setting environment variables on os.environ anymore (the environ of the IDE process) but get_cobc_run_info still check it  to determine the full path of the cobcrunner.

**Comment by GitMensch** [comment]
The same problem seems to occur with compiler checks. When setting the compiler path to cobc.exe and add the appropriate files to PATH setting check compiler says:

~~~~~
---------------------------
Invalid compiler path
---------------------------
Not a valid compiler path, path does not exists: cobc.exe!
---------------------------
OK   
---------------------------
~~~~~

**Comment by ColinDuquesnoy** [comment]
Should be fixed now

![output1](https://cloud.githubusercontent.com/assets/1681217/10737216/44863fea-7c11-11e5-8759-6603a5c8a54a.PNG)
![output2](https://cloud.githubusercontent.com/assets/1681217/10737217/44aee72e-7c11-11e5-94c4-1b2fcb6c39ea.PNG)

**Comment by GitMensch** [comment]
Looks working, but a little bit confusing: the one path is ``D:\Documents\OpenCobolIDE\GnuCOBOL-Win32-MinGW\bin\cobc.exe`` and the other one ``C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL\bin\cobcrun.exe``.

???

**Comment by ColinDuquesnoy** [comment]
Ah right. That's because I have added ``C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL\bin\cobcrun.exe`` to the PATH environment variable of HackEdit (which I use to run OpenCobolIDE).

Hackedit environment variables editor:

![hackeditenvironmentvariables](https://cloud.githubusercontent.com/assets/1681217/10738838/8d97523e-7c19-11e5-99ee-a65ff77fc752.png)


If I remove that variable, I have the correct output:

![capturecobcinfo](https://cloud.githubusercontent.com/assets/1681217/10738855/a263567c-7c19-11e5-89b1-b4fce3e8d5a6.PNG)


Sorry for the confusion ^^

**Comment by GitMensch** [comment]
In this case there is a bug. The PATH setting of OCIDE must prefix current PATH setting from outside. Looks like it currently is only appending PATH.

Please make sure that OCIDE uses the correct path (for call in About OCIDE and compile/run in general) with the setup you had before. This is important for all settings where OCIDE (HackEdit, too) adds stuff to environment variables.

**Comment by ColinDuquesnoy** [comment]
> Looks like it currently is only appending PATH. 

Yes they are appended. I've rewrote the way environment variables are handled (the code is totally different than in v4.6) and forget about this "detail". Thanks for the reminder. I've fixed it in the latest commit.

**Comment by GitMensch** [comment]
Please re-open as -runtime-env was renamed shortly after the implementation in OCIDE.
I suggest to check for `cobcrun --runtime-conf` fist, if this doesn't work try `cobcrun --runtime-env`. As there's **currently** no other option starting with  "runtime" you *could* use the version `cobcrun --runtime` - this should work with both versions (but may brake in the future if any other command line option starting with "runtime" is added). Or use the short option which will not be changed: `cobcrun -r` (this works with both versions).

OR (I think this is the way I'd do this): simply replace `runtime-env` by `runtime-conf` - older versions don't have this and this would be documented already.

**Comment by ColinDuquesnoy** [comment]
`cobcrun -r` looks better as it works with both version. 

Please open a new issue: `[BUG] runtime configuation does not work with recent versions of cobc`
