### ISSUE TITLE
[Enhancement] Add option to save/load preferences

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#229]
One may want to store the preferences and restore them on a different machine (I currently just want to test with different configurations, but this is a special use case ;-).

It would be nice to be able to load only specific attributes (maybe a popup with the title of the preferences [one for each tab], all checked on first entry). Using the same popup for restore would be nice, too.

**Comment by ColinDuquesnoy** [comment]
Yes this could be useful. I'll implement that in hackedit beta (not alpha) and will backport in v4.7.x.

**Comment by ColinDuquesnoy** [comment]
I've changed my mind: I'll implement this first in ocide since I now have the methods to import/export the preferences to a map of strings (added when working on #255)

**Comment by ColinDuquesnoy** [comment]
Implemented. I've added two actions to the "File" menu: "Import preferences"  and "Export preferences".

I haven't implemented the ability to choose the attribute you want to export/import because they are not organised in groups at all (i.e. you will end up with a lots of (too much) keys to choose from).

**Comment by GitMensch** [comment]
Is it possible to group them and allow this "grouped" export to be done in Hackedit?

**Comment by ColinDuquesnoy** [comment]
Options are organized into section in HE so I guess it should work (but I haven't looked into that yet).
