### ISSUE TITLE
[Bug] File-Open borks case of filename

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#239]
Open a file in upper-case in Windows (in this test case ``\\SERVER\SHARE\MY.COB``) on a hard-drive / share which is case-sensitive, this leads to a file not found error

~~~~~
---------------------------
Failed to open path
---------------------------
Failed to open path: [WinError 2] Das System kann die angegebene Datei nicht finden: '\\\\SERVER\\SHARE\\my.cob'
---------------------------
OK   
---------------------------
~~~~~

## System information

- OpenCobolIDE: 4.7.dev37
- GnuCOBOL: GNU Cobol 1.1.0
- Python: 3.4.3 (32bits)
- Qt: 5.5.0
- PyQt: 5.5
- pyqode.core: 2.7.0.dev33
- pyqode.cobol: 2.7.dev0
- pyqode.qt: 2.7.dev0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by GitMensch** [comment]
The unhandled exception in #240 should be fixed before fixing this issue #239 as the bug here is necessary to reproduce #240.

**Comment by ColinDuquesnoy** [comment]
I don't have the means to reproduce it but I guess I know why this happen (on windows case is normalized for comparison but the original path should be used for the actual opening of the file).

So the fix I've pushed is experimental. Comment if you still have the issue and I'll reopen...

**Comment by GitMensch** [comment]
Should work as the file-open dialog let you only exit with a file name selected if it is found - in the case of case-sensitive files this is exactly what's needed.
For what comparison does OCIDE lowercases the path and why does it only do so on Windows?

**Comment by ColinDuquesnoy** [comment]
> For what comparison does OCIDE lowercases the path and why does it only do so on Windows?

This is used to compare file paths, to see if a file is already opened or not. I use `os.path.normcase` which only have an effect on windows. The reason why I do that is because the python interpreter sometimes reports traceback with filepath in lower case (this depends on how the package was installed or if the application that is being run use a custom exception hook and use ``traceback.format_exc``). The user might also be type the full file path in lower case...
