### ISSUE TITLE
[Enhancement] Add ability to switch from free format to fixed and inversely

### ISSUE THREAD

**Issue by eugeniodilo** [OpenCobolIDE/OpenCobolIDE#249]
Selecting some rows and have a _**"shift right"**_ or a _**"shift left"**_ command of _"n"_ columns.
useful to indent some text or to change a source from free format to fixed format and viceversa.

**Comment by ColinDuquesnoy** [comment]
@eugeniodilo Please, stop double posting and please answer the question I asked you.

The question is the same as in pyQode/pyQode#52: **How is that different than the indent/un-indent actions???**

Switching from free format to fixed format involves much more than just shifting rows (you need to adapt the compilation command, make sure the correct comment indicator is used...) So maybe you would like a command that say: "Switch to free format" or "Switch to fixed format"?

**Comment by GitMensch** [comment]
I guess eugeniodilo requested a function to do the intend/un-intend by "n" colums without the need to change "n" in the settings (easily accessed by [F2]). But I'm with Colin and say intend/un-intend is enough.

An option to switch between free and fixed form is really nice although the only things for switching fixed to free are:

* if there's content after column 72 (while this is a missing setting in OCIDE as cobc allows changing this - which may be necessary if you want to work with COBOL sources written for other vendors) and it's not already part of an inline comment: prefix it with ``*>``
* if ``-`` is found in column 7: go further until a line does not start with ``*`` or ``-`` and do the following backwards:
    * if the next item start with a ``'`` or ``"`` add the ``-`` at the end of the previous line after the last ``'`` or ``"`` (skip any comments)
    * if not it's part of a statement, place the next word directly at the end of the previous line [without a space between!] (skip any comments)
* replace ``*`` in column 7 with ``*>``
* replace ``\`` in column 7 with ``*>\`` (won't do the same as there won't be a line break in listing, but necessary for later change free-fixed
* replace ``D`` in column 7 with ``>>D`` (only valid for GnuCOBOL as this is a non-common extension)
* optional: un-intend by 6

An automatic way of combining lines is not useful as the programmer likely has added line breaks in most cases because there should be line breaks.

For free-to fixed: everything listed before in switched order but additional check if a resulting source text would exceeds column 72, if yes: place this source text to the next line with the same intend.

Really not necessary but nice-to-have :-)
Maybe waiting for an HackEdit plugin is a reasonable option.

**Comment by ColinDuquesnoy** [comment]
@GitMensch Thank you for the detailed description. Yes a HackEdit plugin seems best.

**Comment by GitMensch** [comment]
So if this issue is about the conversion free<->fixed format I suggest a title change ;-)

**Comment by ColinDuquesnoy** [comment]
Closing in favor of HackEdit/hackedit#22

**Comment by GitMensch** [comment]
It's perfect for moving this to HE.
This (and the other issues which you recently closed) should be tagged accordingly, maybe add a "wont implement" tag to them?

**Comment by ColinDuquesnoy** [comment]
> his (and the other issues which you recently closed) should be tagged accordingly, maybe add a "wont implement" tag to them?

Yes. I've added the "wontfix" label to the issues marked for milestone 4.7 but not for those marked for the HackEdit milestone. Thanks for the reminder!

**Comment by GitMensch** [comment]
Just for reference: there is an existing COBOL source which you could ship or even ship binary for this tasks (haven't checked the quality for quite a long time but "works" in general"):

svn://svn.code.sf.net/p/open-cobol/contrib/trunk/tools/changeformat

**Comment by ColinDuquesnoy** [comment]
This looks interesting.

> you could ship or even ship binary for this tasks

If I can compile it as standalone executable for all the supported platforms (statically linked with libcob...), I will ship it with HE otherwise users will have to compile it themselves and set it up in HE preferences...

**Comment by GitMensch** [comment]
> If I can compile it as a standalone executable for all the supported platforms (statically linked with libcob...), ...

Of course you can, as you don't need any screen i/o or ISAM you could configure libcob with `--without-db --without-curses` which drops two additional dependencies. GMP/MPIR can be statically linked as you libcob can, but it may be not that simple to do so...

**Comment by ColinDuquesnoy** [comment]
Nice to know. But I'm not sure I'm going to go into the trouble of making that standalone... I'll see when I'll work on HackEdit/hackedit-cobol#24.
