### ISSUE TITLE
[Bug] [Unhandled exception] AttributeError

### ISSUE THREAD

**Issue by ElleryW** [OpenCobolIDE/OpenCobolIDE#258]
## Steps to reproduce

I opened an 18MB file.  I'm not sure if the content of the file was the issue or the size.  This is my first day of using COBOL so I'm afraid I can't be more help...

## Traceback

```
  File "D:\Documents\OpenCobolIDE\open_cobol_ide\controllers\file.py", line 81, in request_open
  File "D:\Documents\OpenCobolIDE\open_cobol_ide\controllers\file.py", line 90, in open_file
  File "D:\Documents\OpenCobolIDE\open_cobol_ide\controllers\edit.py", line 155, in add_editor
  File "D:\Documents\OpenCobolIDE\open_cobol_ide\view\editors\__init__.py", line 15, in update_editor_settings

AttributeError: 'NoneType' object has no attribute 'color_scheme'
```

## System information

- OpenCobolIDE: 4.6.6
- GnuCOBOL: GNU Cobol 1.1.0
- Python: 3.4.3 (32bits)
- Qt: 5.5.0
- PyQt: 5.5
- pyqode.core: 2.6.9
- pyqode.cobol: 2.6.4
- pyqode.qt: 2.7.dev0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
Thank you for reporting!

This is a big file but that should not cause the issue. I guess this is due to the content of your file.

Could you paste the content of your file here so that I can try it by myself? If this is closed source or if you don't want to paste it here, you can also upload it somewhere safe and send me a private email with a link to download the file.

**Comment by ColinDuquesnoy** [comment]
@ElleryW  ping

**Comment by ColinDuquesnoy** [comment]
Closing because of lack of feedback, also the ``add_editor`` function has changed quite a lot so the same error will likely not appear anymore.
