### ISSUE TITLE
Compile/Run freeze

### ISSUE THREAD

**Issue by cuervojones** [OpenCobolIDE/OpenCobolIDE#263]
Gentlemen,
I have read http://opencobolide.readthedocs.org/en/latest/ speciffcaly question 2 ( I cannot compile on Windows. What can I do?) . Added  C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL\bin to PATH and C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL too. However while compiling or running OCIDE always freezes.
Tested the compiler in Preferences:
C:/Program Files (x86)/OpenCobolIDE/GnuCOBOL/bin/cobc.exe (checked compiler - it's working)
Marked the "run in extended terminal" option. No dice.

What i'm missing?

**Comment by ColinDuquesnoy** [comment]
Does it happen with a simple hello world? If no, post the content of your file here (if possible). If yes paste the content of the log file here (%USERPROFILE%\OpenCobolIDE\cache\OpenCobolIDE.log).

**Comment by cuervojones** [comment]
I'm trying with another, more simpler program and it compiled (at least did syntax check) however after correcting all alignments it generates :" gcc: error: online\bin\ct001.exe: No such file or directory"
I've attached the both programs. SFIN011 is the more complex one that locks completely.
CT001 is the one that generated the error above.
[SFIN011.txt](https://github.com/OpenCobolIDE/OpenCobolIDE/files/36918/SFIN011.txt)
[ct001.txt](https://github.com/OpenCobolIDE/OpenCobolIDE/files/36919/ct001.txt)

**Comment by ColinDuquesnoy** [comment]
Thanks. I'll have a look ASAP (but probably not today).

**Comment by cuervojones** [comment]
Don't know if it's relevant but all of them been made/compiled/working on
Microfocus Net Express 5.0/5.1.

2015-11-17 14:31 GMT-02:00 Colin Duquesnoy <notifications@github.com>:

> Thanks. I'll have a look ASAP (but probably not today).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenCobolIDE/OpenCobolIDE/issues/263#issuecomment-157422002>
> .
>



-- 

Felipe Alvares
[image: https://]about.me/felipe.alvares
<https://about.me/felipe.alvares?promo=email_sig>

**Comment by GitMensch** [comment]
@cuervojones I've just rechecked this:
The reason OCIDE locks is the setting "Auto detect and compile submodules". As a workaround: deactivate this and try again.
@ColinDuquesnoy I guess there is a bug in the dependency tracker?

After changing this I get messages about missing copies, which is expected.

The other error is likely because of some path issue. I guess "online\bin" is the setting for "Output directory"? If yes: try to remove the setting and try again. If it works try "online/bin/".

As a workaround: If your machine has Visual Studio (or a Windows SDK) installed get the nightly 2.x bin package from https://sourceforge.net/projects/open-cobol/files/gnu-cobol/2.0/ unpack it somewhere, set the preferences accordingly and retest (you'll at least won't see an error from gcc...).

**Comment by ColinDuquesnoy** [comment]
> @ColinDuquesnoy I guess there is a bug in the dependency tracker?

Yes the bug is with the dependency tracker regex ([Catastrophic Backtracking](http://www.regular-expressions.info/catastrophic.html)). I found it yesterday night but was too tired to actually fix it or drop comment.

**Comment by ColinDuquesnoy** [comment]
Should be fixed in master branch.

@cuervojones  there won't be a new release before one or two weeks so I suggest to simply turn off ``Auto detect and compile submodules`` in the compiler preferences.
