### ISSUE TITLE
[Minor Bug] file extension should be rececked after SAVE-AS

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#264]
I've opened a txt-file (read only), see the nice message "file is read only", used save-as "file.cob".
The syntax highlighting is still missing and more important: to get the compilation option you need to close and reopen the file.
## System information
- OpenCobolIDE: 4.7.dev58
- Python: 3.4.3 (32bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.7.0.dev33
- pyqode.cobol: 2.7.dev0
- pyqode.qt: 2.7.dev0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
Well, there is actually no other way around closing the tab and reopening it (because we use different classes for different type of editors, GenericCodeEdit vs CobolCodeEdit and the type is set when you open a file).

But this could be done automatically if the mimetype changed (i.e. close the GenericCodeEdit and open a new CobolCodeEdit). 

Since this is a pyqode specific issue, I'll make the change in pyqode.core. That way the fix will be available for both HE and OCIDE (4.7.x).

**Comment by GitMensch** [comment]
Just as a questions (no pressure): Is this a candidate for the upcoming release?

**Comment by ColinDuquesnoy** [comment]
Nope, I'd like to tackle this issue in pyqode 3.0.

**Comment by GitMensch** [comment]
OK, thanks for the info.
