### ISSUE TITLE
Additional and configurable menu items

### ISSUE THREAD

**Issue by eugeniodilo** [OpenCobolIDE/OpenCobolIDE#277]
It would be very helpful to have more flexibility in the configuration of the IDE.
I would like to enter or set additional custom menu items to which to associate command to the user's choice.
For example if you could enter 10 menu items these would associate the execution of the following commands.
menu item 1 -> command: cobc  -help   description: Display compiler help information  
menu item 2 -> command: cobc  -info description: Display compiler built information 
menu item 3 -> command: cobc -V  description:  Display compiler version
menu item 4 -> command: cobc -list-reserved description: Display COBOL reserved words 
menu item 5 -> command: cobc -list-system description: Display COBOL system routines
menu item 6 -> command: cobc- list-mnemonics  description: Display COBOL mnemonic names 
menu item 7 -> command: cobc -list-intrinsics description: Display COBOL intrinsic functions 
menu item 8 -> command: printcbl  %1 to execute the printcbl utility on current filename .cbl source (where %1 is the current filename.cbl source)
menu item 9 -> command: cobxref  %1 to execute the cobxref utility on current filename .cbl source
(where %1 is the current filename.cbl source)
menu item 10 -> command: animator   %1    to execute Federico's Animator preprocessing and a cobc compilation  
(where %1 is the current filename.cbl source)
menu item 11 -> command:  %1    to execute the current filename .exe 
(where %1 is the current filename.cbl source)
menu item 12 -> command:  AcroRd32 GNUCobol2-A4.pdf   to display Gary's Manual
... and so on ...

What do you think about ?

**Comment by ColinDuquesnoy** [comment]
OpenCobolIDE 4.7 is about to be released. After that release it will enter in maintainance mode, no new features will be accepted. That being said, "External tools" integration [is planned](https://github.com/HackEdit/hackedit/issues/35) for HackEdit beta. Therefore, I am closing this. I'll let you know when this is available in HackEdit.

**Comment by eugeniodilo** [comment]
​Hi Colin, thanks for your answer. I respect your decision but I am very
sorry. I think the GnuCOBOL compiler needs its own specific environment.
There are many editors available but only OpenCobolIDE is dedicated to
GnuCOBOL developers and this specificity is a great value. GnuCOBOL does
not have its own IDE if not OpenCobolIDE that today has reached a very
attractive level of stability, and functionality.
How come you took your decision?
what, we GnuCOBOL developers,  will find in HackEdit as an additional value
?​


2016-01-21 21:02 GMT+01:00 Colin Duquesnoy <notifications@github.com>:

> OpenCobolIDE 4.7 is about to be released. After that release it will enter
> in maintainance mode, no new features will be accepted. That being said,
> "External tools" integration is planned
> <https://github.com/HackEdit/hackedit/issues/35> for HackEdit beta.
> Therefore, I am closing this. I'll let you know when this is available in
> HackEdit.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenCobolIDE/OpenCobolIDE/issues/277#issuecomment-173692309>
> .
>



-- 

*Eugenio Di Lorenzo*

[image: Descrizione: Descrizione: Descrizione: Descrizione:
C:\Cedacri\firma\gogreen.gif]  Think green, read from the screen!

**Comment by ColinDuquesnoy** [comment]
I am primarily a Python, C/C++ and Qt developer. I wrote OpenCobolIDE years
ago when I was attempting some COBOL lessons at school and could not find a
good IDE to work with on GNU/Linux. Nowadays I don't even work with COBOL but
keep maintaining the IDE because I like the language and it's a good showcase
of what you can do with pyQode.  

Two years ago I've started to work on a python IDE. I quickly realised that
the codebase was very similar to OCIDE and it would take me too much time to
maintain both so I started to work on HackEdit (keep in mind I am doing all
this during my freetime, as a hobby project).

  

The ultimate goal of HackEdit is that it should allow the user to turn it into
a language/technology specific IDE (i.e. GnuCOBOL integration should be as
good as in OCIDE).

  

You shouldn't be afraid or sorry, HackEdit + the cobol plugins give you an
even better IDE than OCIDE, because HE already have all the generic features
you expect from an IDE (searching through all the project files, goto dialog
like in Sublime text, external tools, vcs integration,...) and the COBOL
plugins provides all the features you can find in OCIDE (and even more, i.e.
you can configure own pre-parsers, there will be a debugger,...).

  

You can really consider HackEdit (with the COBOL plugins) as the  next major
version of OCIDE. You won't loose any feature!

  

I know at least one OCIDE user who already made the switch to HE
(http://sourceforge.net/p/open-cobol/discussion/help/thread/e42d9701/#801d).

  

At the moment, the main drawbacks of HE are that there is no windows installer
and there are shortcomings with file indexing (especially for big projects,
should be ok for small projects). Those points should be fixed for the beta
release. I encourage you to try out HackEdit (open an issue on the HE tracker
if you have trouble installing it).

  

  

Colin Duquesnoy

_26, rue de l'Harmonie  
_

_4800 Verviers_

_+32 475 33 56 34_  

[colin.duquesnoy@gmail.com](mailto:colin.duquesnoy@gmail.com
"mailto:colin.duquesnoy@gmail.com" )

> On Jan 21 2016, at 9:57 pm, eugeniodilo &lt;notifications@github.com&gt;
wrote:  
​Hi Colin, thanks for your answer. I respect your decision but I am very  
sorry. I think the GnuCOBOL compiler needs its own specific environment.  
There are many editors available but only OpenCobolIDE is dedicated to  
GnuCOBOL developers and this specificity is a great value. GnuCOBOL does  
not have its own IDE if not OpenCobolIDE that today has reached a very  
attractive level of stability, and functionality.  
How come you took your decision?  
what, we GnuCOBOL developers, will find in HackEdit as an additional value  
?​  
  
  
2016-01-21 21:02 GMT+01:00 Colin Duquesnoy &lt;notifications@github.com&gt;:  
  
&gt; OpenCobolIDE 4.7 is about to be released. After that release it will
enter  
&gt; in maintainance mode, no new features will be accepted. That being said,  
&gt; "External tools" integration is planned  
&gt; &lt;https://github.com/HackEdit/hackedit/issues/35&gt; for HackEdit beta.  
&gt; Therefore, I am closing this. I'll let you know when this is available in  
&gt; HackEdit.  
&gt;  
&gt; —  
&gt; Reply to this email directly or view it on GitHub  
&gt; &lt;https://github.com/OpenCobolIDE/OpenCobolIDE/issues/277#issuecomment-
173692309&gt;  
&gt; .  
&gt;  
  
  
  
\--  
  
*Eugenio Di Lorenzo*  
  
[image: Descrizione: Descrizione: Descrizione: Descrizione:  
C:\Cedacri\firma\gogreen.gif] Think green, read from the screen!  

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/OpenCob
olIDE/OpenCobolIDE/issues/277#issuecomment-173705499).![](https://github.com/n
otifications/beacon/ABmnQbQoAc_H-GIKLGAh-jB95RshIL3lks5pcT2ugaJpZM4HJynv.gif)

**Comment by eugeniodilo** [comment]
Hi Colin, I'm using your editor with a lot of satisfaction. I think it is really important for gnucobol project. I re-opened this post because more and more I believe it is important to be able to run the debugger TP_DEBUGGER from Federico Priolo. For this it needs very little. Just to exceute animator.exe youprogram.cob.Similarly all the other options I have mentioned can be new fixed menu items. No need to have the ability to customize variables menu items. For example, a menu item that opens the Cobol Manual I think should be very simple for you to add it in OCIDE.

**Comment by ColinDuquesnoy** [comment]
OCIDE being in maintenance mode, I am afraid the answer is no, at least for big features such as TP-COBOL integration (OCIDE architecture is not well suited to add a new preprocessing step, this looks simple but will require quite a lot of work and testing, this will be in HackEdit). 

That being said I might add very simple features such as the link to the manual. But don't expect this to be in soon, I have a lots of other task to do on other projects and I planned not to work on OCIDE before a few monts.
