### ISSUE TITLE
GnuCOBOL is on version 2.0, whereas IDE is on 1.1.0

### ISSUE THREAD

**Issue by askadian** [OpenCobolIDE/OpenCobolIDE#330]
*_This is not an issue. *_

Is there a way I can use GnuCOBOL Version 2.0 with OpenCOBOL IDE instead of 1.1.0 that it comes with. Thanks!!

**Comment by ColinDuquesnoy** [comment]
Yes. Download the latest GnuCOBOL from sourceforge: https://sourceforge.net/projects/open-cobol/files/gnu-cobol/2.0/ (if you're using a 64bit version of DB2 you will need to install a 64 bit of GnuCOBOL such as [this one](https://sourceforge.net/projects/open-cobol/files/gnu-cobol/2.0/gnu-cobol-2.0_nightly_r697_only_for_testing_purposes_win32_and_x64_vc11_bin.7z/download)).

And follow the [documentation](http://opencobolide.readthedocs.io/en/latest/advanced.html#setup-a-custom-compiler-on-windows) about setting up a custom compiler. (if using a 64 bit compiler, you'll need to set the path to cobc in bin_x64 and set vcvarsall architecture to x64).

**Comment by askadian** [comment]
I downloaded the latest GnuCOBOL from sourceforge(given link) and extracted the files/folders in following directory: C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL (I renamed the earlier GnuCOBOL Folder as GnuCOBOL - backup).

After that I changed the compiler settings as follows:
Compiler Path: C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL\bin_x64\cobc.exe
for other fields, please see the screenshot attached.
![opencobolide for gnucobol version 2 0](https://cloud.githubusercontent.com/assets/8684201/15212360/cdade244-185d-11e6-8348-6133d92c4c75.jpg)

I am facing a problem in setting up vcvarsall architecture to x64 as mentioned. I do not have vcvarsall.exe file. Where do I have to find it? I tried to install VC++ Studio 2010 and it does install on my m/c, but there is not vcvars.

So, when I do a check compiler, I get the following error:
```
Output:'cl' is not recognized as an internal or external command,
operable program or batch file.

Tips:
- You might need to adapt the environment variables set by the IDE to make it work.
- If you see MinGW related errors ensure that there is no additional installation of MinGW in C:\MinGW

```

**Comment by ColinDuquesnoy** [comment]
> I  am facing a problem in setting up vcvarsall architecture to x64 as mentioned. I do not have vcvarsall.exe file. Where do I have to find it?

Please, read the documentation link I gave you (http://opencobolide.readthedocs.io/en/latest/advanced.html#setup-a-custom-compiler-on-windows). You need to set the path to vcvarsall.**bat**, you can find it there ``c:\Program Files(x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat``

**Comment by askadian** [comment]
I found the vcvarsall.bat file at **_C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat_**. Now when I do the check compiler, I get the following erros:
```
Complier check failed:

Exit code: -1
Output: C:\GnuCobol\libcob.h(25): fatal error C1083: Cannot open include file: 'gmp.h': No such file or directory

Tips:
- You might need to adapt the environment variables set by the IDE to make it work.
- If you see MinGW related errors ensure that there is no additional installation of MinGW in C:\MinGW
```

**Comment by eugeniodilo** [comment]
Hi askadian ,
follow indication at this image.
I downloaded the GNU COBOL compiler and it works from OpenCobolIDE .
You dint'need  vcvarsall. 
You have only to customize OpenCobolIDE settings.


![image](https://cloud.githubusercontent.com/assets/13390725/15227660/9b84ab92-1888-11e6-8ceb-da40d07c0d36.png)

**Comment by eugeniodilo** [comment]
Obviuosly You have to SET the GNU COBOL ENVIRONMENT variables  COB_*
![image](https://cloud.githubusercontent.com/assets/13390725/15227984/016ded3c-188a-11e6-932c-605d9389985c.png)

**Comment by ColinDuquesnoy** [comment]
@eugeniodilo  He is using a msvc build (64 bits) so vcvarsall is needed.

@askadian Your settings look OK, but it looks like you have a conflicting installation in C:\GnuCobol (I say that because the actual error message seems to be coming from ``C:\GnuCobol\libcob.h(25)``). If you do have a c:\GnuCobol folder, you might want to rename it and see if it works better.

But this shouldn't happen at all. I'd like to have a look at the OCIDE debug log: goto the ``About dialog`` -> ``Logs`` -> Change log level to ``DEBUG``, restart ocide and paste the log output here. It might also help if you could paste the output of ``About->GnuCOBOL``

**Comment by askadian** [comment]
@ColinDuquesnoy I renamed the GnuCOBOL folder at C:/GnuCOBOL but the error was still there.
```
Complier check failed:

Exit code: -1
Output:
Tips:
- You might need to adapt the environment variables set by the IDE to make it work.
- If you see MinGW related errors ensure that there is no additional installation of MinGW in C:\MinGW

```
I renamed C:\MinGW also.

Attached the log files for OCIDE and GnuCOBOL. Thanks!!

[GnuCOBOL.txt](https://github.com/OpenCobolIDE/OpenCobolIDE/files/266144/GnuCOBOL.txt)
[OCIDE D16051016.txt](https://github.com/OpenCobolIDE/OpenCobolIDE/files/266145/OCIDE.D16051016.txt)

**Comment by askadian** [comment]
Did you get time to look into the issue? Thanks!!

**Comment by ColinDuquesnoy** [comment]
No, sorry, I am on holiday this week, with limited internet access. I'll have a look ASAP.

**Comment by GitMensch** [comment]
@askadian I just had a lool at the files.
I *think* you removed the old folder `C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL` and placed the folder of the new version to the same place, this correct?

As you want to use a VC based installation it doesn't matter if there is a C:\MinGW folder or not.

There are conflicting issues on your machine: either set all `COB_` variables to point to the correct folder (COB_CFLAGS and COB_LDFLAGS are missing [see your uploaded GnuCOBOL.txt how to set it]) or uncheck all those settings to use the compiler-inbuild versions, move the GnuCOBOL folder back to `C:\GnuCOBOL`, set `PATH` to C:\GnuCOBOL\bin_x64` and the compiler to `cobc.exe`. This should work.

@ColinDuquesnoy I highly suggest to add `-v` to the command lines for checking the GnuCOBOL compiler as this shows much more information what is actually done (works at least since OC 0.3, works best in GnuCOBOL 2.x of course).
A real issue in OCIDE can be seen from the logs:
"check compiler" has `PATH=C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL\bin_x64;[...]` and `command: "C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL\bin_x64\cobc.exe" [...]` while
"getting cobc version" has `PATH=C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL\bin;[...]` and `command: "C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL\bin\cobc.exe" --version`.

**Comment by ColinDuquesnoy** [comment]
@GitMensch not an issue, this happens before user changed compiler config or after dialog was canceled. I can see one version check where the correct path is used. I'll add the -v flag in next release....

**Comment by GitMensch** [comment]
@askadian Can we close this question?
