### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by dslackw** [OpenCobolIDE/OpenCobolIDE#353]
When try run opencobolide in python 3.5:

Traceback (most recent call last):
  File "/usr/bin/opencobolide", line 9, in <module>
    load_entry_point('OpenCobolIDE==4.7.4', 'gui_scripts', 'opencobolide')()
  File "/usr/lib64/python3.5/site-packages/open_cobol_ide/main.py", line 29, in main
    override_sys_path()
  File "/usr/lib64/python3.5/site-packages/open_cobol_ide/main.py", line 20, in override_sys_path
    assert 'open_cobol_ide' in pyqode.core.__file__
AssertionError

**Comment by ColinDuquesnoy** [comment]
This means you have another version of pyqode in your python system packages. Since v4.7 ocide already includes the pyqode packages which might conflict with those installed on your system. The assertion is a debug assert I've forgot to remove...

You have two solutions:
- uninstall pyqode:
```
pip3 uninstall pyqode.core pyqode.qt pyqode.cobol
```
- use the latest ocide version from github master branch (which does not have this assertion anymore) (and make sure to update pyqode to the latest version from pypi)

```
pip3 install git+https://github.com/OpenCobolIDE/OpenCobolIDE.git --upgrade
pip3 install pyqode.core pyqode.qt pyqode.cobol --upgrade
```

**Comment by dslackw** [comment]
Fixed!
Thank you!
