### ISSUE TITLE
Run in external terminal does not work anymore, error code seems to be uninterpreted.

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#370]
### Description

Running the module without "run in external terminal" lead to "Redirection not supported" (a curses message).

Therefore I've enabled this option but only see "launched in external terminal" - nothing happens. According to the application log the entry that was started is wrong:

```
open_cobol_ide.controllers.cobol::running program in external terminal: d:\programme\entwicklung\python\pythonw.exe D:\Programme\Entwicklung\GnuCOBOL\GC20base-vbisam\bin\cobcrun.EXE d:\programme\entwicklung\python\lib\site-packages\open_cobol_ide\extlibs\pyqode\core\tools\console.py GC01BOX
```

I'd say the correct version may be

```
d:\programme\entwicklung\python\pythonw.exe d:\programme\entwicklung\python\lib\site-packages\open_cobol_ide\extlibs\pyqode\core\tools\console.py D:\Programme\Entwicklung\GnuCOBOL\GC20base-vbisam\bin\cobcrun.EXE GC01BOX
```

Interesting: there is no output of an error code...

### System information

- Operating System: Windows
- OpenCobolIDE: 4.7.6.dev0
- GnuCOBOL: cobc (GnuCOBOL) 2.0.0
- Python: 3.4.4 (64bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.11.0.dev0
- pyqode.cobol: 2.11.0.dev0
- pyqode.qt: 2.10.0
- pygments: 2.1.3
- QDarkStyle: 2.2.1

**Comment by ColinDuquesnoy** [comment]
Should be fixed, this was a rather corner case when running from source checkout without the pyqode tools in PATH.

There are no error reporting because the only way I've found to launch an external terminal is to run start a detached process. Since the process starts correctly (python), no exception are thrown (they would be thrown if the python interpreter path could not be found).

**Comment by GitMensch** [comment]
I see, retested: works fine.
