### ISSUE TITLE
Cobol Project Support

### ISSUE THREAD

**Issue by ColinDuquesnoy** [OpenCobolIDE/OpenCobolIDE#84]
I am opening this issue to discuss the possibility to add project support to the IDE.

OpenCobolIDE has been designed to work on a single file basis. You open a file and compile it.  Well, this is not entirely true, actually there is a sort of implicit project support: the IDE will first parse the file you want to compile to detect its dependencies and compile them before compiling the file itself.

Not having a project concept makes the IDE very easy to use for a beginner (there is no makefile, not config to setup) but can be very limitating for the experts.

Introducing the concept of project would bring the following benefits:
 - ability to specify which file should be compiled and how. With the current design, the compiler properties are applied globally on every file that get compiled.
 - ability to add VCS support (#83)

A very important point to consider when implementing this feature is **that it is very important to keep the ability to open and compile a single file.** This means that we must have **two different kind of windows**: a single document window that you will use to work on a single unit (mainly for the beginners) and a project view with vcs integration and all the bells and whistles a project can offer. **This means a complete redesign of the application!**

Also if we implement project support, **we need to find a build system for building the project sources** but I am not sure if there is a standard build system for cobol (I don't want a makefile because IMHO this goes against the philosophy of an IDE where you should be able to add new source files without editing anything, using pure GUI actions).

@bofinken @Astalaseven @LuizFlavio @martyheyman @abbhishek Any thoughts on this? What build system are you using for building your cobol projects and what would you like to see in OpenCobolIDE?

**Comment by Bofinken** [comment]
I don't remember if I have answered this before, but at home I only compile
single files at work I do the same, but I also compile whole projects with
Jenkins as the continuous integration (CI) tool.

 

 

  _____  

Från: Colin Duquesnoy [mailto:notifications@github.com] 
Skickat: den 19 december 2014 15:15
Till: OpenCobolIDE/OpenCobolIDE
Kopia: Bofinken
Ämne: [OpenCobolIDE] Cobol Project Support (#84)

 

I am opening this issue to discuss the possibility to add project support to
the IDE.

OpenCobolIDE has been designed to work on a single file basic. You open a
file and compile it. Well, this is not entirely true, actually there is a
sort of implicit project support: the IDE will first parse the file you want
to compile to detect its dependencies and compile them before compiling the
file itself.

Not having a project concept makes the IDE very easy to use for a beginner
(there is no makefile, not config to setup) but can be very limitating for
the experts.

Introducing the concept of project would bring the following benefits:

*	ability to specify which file should be compiled and how. With the
current design, the compiler properties are applied globally on every file
that get compiled.
*	ability to add VCS support (#83
<https://github.com/OpenCobolIDE/OpenCobolIDE/issues/83> )

A very important point to consider when implementing this feature is that it
is very important to keep the ability to open and compile a single file.
This means that we must have two different kind of windows: a single
document window that you will use to work on a single unit (mainly for the
beginners) and a project view with vcs integration and all the bells and
whistles a project can offer. This means a complete redesign of the
application!

Also if we implement project support, we need to find a build system for
building the project sources but I am not sure if there is a standard build
system for cobol (I don't want a makefile because IMHO this goes against the
philosophy of an IDE where you should be able to add new source files
without editing anything, using pure GUI actions).

@bofinken <https://github.com/bofinken>  @Astalaseven
<https://github.com/Astalaseven>  @LuizFlavio
<https://github.com/LuizFlavio>  @martyheyman
<https://github.com/martyheyman>  @abbhishek <https://github.com/abbhishek>
Any thoughts on this? What build system are you using for building your
cobol projects?

—
Reply to this email directly or view it on GitHub
<https://github.com/OpenCobolIDE/OpenCobolIDE/issues/84> .
<https://github.com/notifications/beacon/AGDDmEHHGnW5Xf6Wy9lMS_5TwVQDSBuZks5
nZCp2gaJpZM4DKjJb.gif>

**Comment by ColinDuquesnoy** [comment]
Thanks @Bofinken but what build system are you using to actually compile the whole project? A shell script, a makefile?

**Comment by Bofinken** [comment]
Using a Jenkins script, checking out the project from subversion and
compiling each program in a nightly build.

 

 

  _____  

Från: Colin Duquesnoy [mailto:notifications@github.com] 
Skickat: den 18 februari 2015 20:29
Till: OpenCobolIDE/OpenCobolIDE
Kopia: Bofinken
Ämne: Re: [OpenCobolIDE] Cobol Project Support (#84)

 

Thanks @Bofinken <https://github.com/Bofinken>  but what build system are
you using to actually compile the whole project? A shell script, a makefile?

—
Reply to this email directly or view
<https://github.com/OpenCobolIDE/OpenCobolIDE/issues/84#issuecomment-7493072
0>  it on GitHub.
<https://github.com/notifications/beacon/AGDDmK4EItKTu1pLtgg_JwXFOuWbSSmCks5
ntN-RgaJpZM4DKjJb.gif>

**Comment by ColinDuquesnoy** [comment]
I implemented project support in HackEdit. Support for other build system will be available through plugins (I plan to add support for at least auto-tools and makefiles)

Therefore I am closing this issue.
